app = "brzaguza"
primary_region = "cdg"

[build]
  image = "ghcr.io/tminaorg/brzaguza:latest"

[env]
  BRZAGUZA_SERVER_FRONTENDURLS = "https://brzaguza.rs"
  BRZAGUZA_ENGINES_GOOGLE_ENABLED = "false"
  BRZAGUZA_ENGINES_QWANT_ENABLED = "false"
  BRZAGUZA_ENGINES_STARTPAGE_ENABLED = "false"
  BRZAGUZA_ENGINES_YEP_ENABLED = "false"

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/healthz"
