app = "hearchco"
primary_region = "cdg"

[build]
  image = "ghcr.io/hearchco/hearchco:latest"

[env]
  HEARCHCO_SERVER_CACHE_TYPE = "redis"
  HEARCHCO_SERVER_FRONTENDURL = "https://hearch.co"

[http_service]
  internal_port = 3030
  force_https = false # needed for flycast
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    hard_limit = 10
    soft_limit = 5

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/healthz"
