name: Testing CI

on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '37 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # git
      - uses: actions/checkout@v3

      # go
      - uses: actions/setup-go@v4
        with:
          go-version: stable

      # go:generate
      - name: Generate go code from go:generate comments
        run: make install

      # go:build
      - name: Build project
        run: make build

      # go:test
      - name: Test units
        run: make test