name: Testing CI

on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '37 13 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: stable

      # go:generate
      - name: Generate go code from go:generate comments
        run: make install

      # go:build
      - name: Build project
        run: make build

      # go:test
      - name: Test units
        run: make test
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Optional: allow read access to pull request. Use with `only-new-issues` option.
      # pull-requests: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: stable

      # go:generate
      - name: Generate go code from go:generate comments
        run: make install

      # lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true