name: Testing CI

on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '37 13 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: stable

      # go:generate
      - name: Generate go code from go:generate comments
        run: make install

      # go:build
      - name: Build project
        run: make build

      # go:test
      - name: Test units
        run: make test
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: stable
          cache: false

      # go:generate
      - name: Generate go code from go:generate comments
        run: make install

      # lint
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest