name: Docker CI/CD

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
    steps:
      # git
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - run: git fetch --force --tags

      # go
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      
      # qemu
      - uses: docker/setup-qemu-action@v2
      
      # registry
      - uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # go:generate
      - name: Generate go code from go:generate comments
        run: make install

      # snapshot
      - name: Snapshot on non-tag
        uses: goreleaser/goreleaser-action@v5
        if: startsWith(github.ref, 'refs/tags/') == false
        with:
          version: latest
          args: release --snapshot --clean --config goreleaser/develop.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      ## go:test
      - name: Test units
        if: startsWith(github.ref, 'refs/tags/') == false
        run: make test

      # release
      - name: Release on tag
        uses: goreleaser/goreleaser-action@v5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean --config goreleaser/release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      ## artifacts
      - name: Artifact Linux
        uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: build_linux
          path: dist/*linux*

      - name: Artifact Darwin
        uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: build_darwin
          path: dist/*darwin*
      
      - name: Artifact Windows
        uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: build_windows
          path: dist/*windows*