name: golangci-lint

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # git
      - uses: actions/checkout@v3

      # go
      - uses: actions/setup-go@v4
        with:
          go-version: stable

      # lint
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest